#!/bin/bash
# PURPOSE: Aggregates all # TODO: comments from src/ and tests/ into CODE_TODOS.md
# Creates a read-only dashboard view for human convenience.

OUTPUT_FILE="CODE_TODOS.md"
# Define search directories relative to the Git root (where the hook runs)
PROJECT_SUBDIR="zeroth_law"
SEARCH_DIRS=("${PROJECT_SUBDIR}/src" "${PROJECT_SUBDIR}/tests") # Add other dirs if needed

RG_PATH="$HOME/.local/share/cargo/bin/rg"

# Check if rg is installed at the specified path relative to HOME
if ! command -v "${RG_PATH}" &> /dev/null
then
    echo "Error: ripgrep (rg) not found at expected path: ${RG_PATH}"
    exit 1
fi

# Create or clear the output file
echo "# Code-Level TODOs (Auto-Generated)" > "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"
echo "Generated: $(date --iso-8601=seconds)" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"
echo "Source | Line | TODO Comment" >> "${OUTPUT_FILE}"
echo "-------|------|--------------" >> "${OUTPUT_FILE}"

# Use rg to find TODOs, format output as Markdown table rows
# --glob '*.py' ensures we only search Python files
# Format: | filename | line_number | comment_text |
"${RG_PATH}" --no-heading --line-number --glob '*.py' '# TODO:' "${SEARCH_DIRS[@]}" | \
    awk -F':' '{gsub(/^[ \t]+/, "", $3); printf "| %s | %s | %s |\\n", $1, $2, $3}' >> "${OUTPUT_FILE}"

echo "" >> "${OUTPUT_FILE}"
echo "NOTE: This file is auto-generated by scripts/generate_code_todos.sh. Do not edit directly." >> "${OUTPUT_FILE}"

echo "Generated ${OUTPUT_FILE}" 