#!/bin/bash
# PURPOSE: Aggregates all # TODO: comments from src/ and tests/ into CODE_TODOS.md
# Creates a read-only dashboard view for human convenience.

# echo "DEBUG: generate_code_todos.sh starting..."

set -e # Exit immediately if a command exits with a non-zero status.
set -o pipefail # Exit status of the last command that threw a non-zero exit code is returned.

# Determine Git root directory reliably
GIT_ROOT=$(git rev-parse --show-toplevel)
if [ -z "${GIT_ROOT}" ]; then
    echo "Error: Failed to determine Git repository root." >&2
    exit 1
fi
# echo "DEBUG: Git root detected as: ${GIT_ROOT}"

PROJECT_SUBDIR="zeroth_law"
# Define output file path relative to determined Git root
OUTPUT_FILE="${GIT_ROOT}/${PROJECT_SUBDIR}/CODE_TODOS.md"
# Define search directories relative to determined Git root
SEARCH_DIRS=("${GIT_ROOT}/${PROJECT_SUBDIR}/src" "${GIT_ROOT}/${PROJECT_SUBDIR}/tests")

RG_PATH="$HOME/.local/share/cargo/bin/rg"
TMP_RG_OUT="${GIT_ROOT}/${PROJECT_SUBDIR}/rg_output.tmp"

# Check if rg is installed at the specified path relative to HOME
if ! command -v "${RG_PATH}" &> /dev/null
then
    echo "Error: ripgrep (rg) not found at expected path: ${RG_PATH}" >&2
    exit 1
fi

# echo "DEBUG: Writing header to ${OUTPUT_FILE}"
# Create or clear the output file
echo "# Code-Level TODOs (Auto-Generated)" > "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"
echo "Generated: $(date --iso-8601=seconds)" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"
echo "Source | Line | TODO Comment" >> "${OUTPUT_FILE}"
echo "-------|------|--------------" >> "${OUTPUT_FILE}"

# Step 1: Run rg and save raw output to temp file
# echo "DEBUG: Running rg, searching ${SEARCH_DIRS[*]}, outputting to ${TMP_RG_OUT}"
"${RG_PATH}" --no-heading --line-number --glob '*.py' '# TODO:' "${SEARCH_DIRS[@]}" > "${TMP_RG_OUT}" || echo "rg command failed! Exit code: $?"

# Step 2: Process temp file with awk and append to final output
# echo "DEBUG: Running awk on ${TMP_RG_OUT}, appending to ${OUTPUT_FILE}"
if [ -s "${TMP_RG_OUT}" ]; then # Check if temp file is not empty
    # Pass GIT_ROOT and PROJECT_SUBDIR to awk to remove the correct prefix
    awk -F':' -v git_root="${GIT_ROOT}/" -v proj_subdir="${PROJECT_SUBDIR}/" \
    '{
        path = $1;
        prefix_to_remove = git_root proj_subdir; # Construct full prefix
        sub(prefix_to_remove, "", path); # Remove the full prefix
        comment = substr($0, index($0, "# TODO:") + length("# TODO:"));
        sub(/^[ \t]+/, "", comment); # Remove leading space from comment
        printf "| %s | %s | %s |\n", path, $2, comment
    }' "${TMP_RG_OUT}" >> "${OUTPUT_FILE}" || echo "awk command failed! Exit code: $?"
# else
    # echo "DEBUG: Temp file ${TMP_RG_OUT} is empty or non-existent, skipping awk."
fi
# echo "DEBUG: awk processing finished."

# Step 3: Clean up temp file
rm -f "${TMP_RG_OUT}"
# echo "DEBUG: Cleaned up temp file."

echo "" >> "${OUTPUT_FILE}"
echo "NOTE: This file is auto-generated by scripts/generate_code_todos.sh. Do not edit directly." >> "${OUTPUT_FILE}"

echo "Generated ${OUTPUT_FILE}" # Final script output for hook runner