# {{ cookiecutter.project_name }}.toml
# Project-specific configuration file

[app]
name = "{{ cookiecutter.project_name }}"
version = "0.1.0"
description = "A project created with the Zeroth Law AI Framework"
debug = false

[logging]
level = "INFO"
format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
date_format = "%Y-%m-%d %H:%M:%S"
log_file = null

[paths]
data_dir = "data"
output_dir = "output"
cache_dir = ".cache"

[limits]
max_line_length = 140
min_docstring_length = 10
max_executable_lines = 300
max_function_lines = 30
max_function_length = 30
max_cyclomatic_complexity = 8
max_parameters = 7

[penalties]
missing_header_penalty = 20
missing_footer_penalty = 10
missing_docstring_penalty = 2

# List of glob patterns to ignore in various operations
ignore_patterns = [
    "**/__pycache__/**",
    "**/.git/**",
    "**/.venv/**",
    "**/venv/**",
    "**/*.pyc",
    "**/.pytest_cache/**",
    "**/.coverage",
    "**/htmlcov/**",
    ".*\\.egg-info.*",
] 